### ISSUE TITLE
Update the nuget package

### ISSUE THREAD

**Issue by lorddev** [StackExchange/MarkdownSharp#2]
https://www.nuget.org/packages/MarkdownSharp/ shows version 1.13.0. It doesn't incorporate any of the commits made in the last 6 years.

**Comment by NickCraver** [comment]
Version 2.0.5 (breaking since I removed `MarkdownOld` is publishing to NuGet now: https://www.nuget.org/packages/MarkdownSharp/2.0.5 Enjoy!
