### ISSUE TITLE
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point

### ISSUE THREAD

**Issue by sairajreddy** [StackExchange/MarkdownSharp#5]
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\MarkdownSharp-master\MarkdownSharp\MarkdownSharp.csproj]

`Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/20/2018 12:23:29 PM.
Project "C:\Users\b-sarajr\Documents\SB\3. Project Files\1. MEC\MarkdownSharp-master\MarkdownSharp.sln" on node 1 (rest
ore target(s)).
ValidateSolutionConfiguration:                                                                                            Building solution configuration "Debug|Any CPU".
Restore:
  Nothing to do. None of the projects specified contain packages to restore.
Done Building Project "C:\Users\b-sarajr\Documents\SB\3. Project Files\1. MEC\MarkdownSharp-master\MarkdownSharp.sln" (
restore target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.62
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\msbuild.exe /bl .\MarkdownSharp.sln
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 3/20/2018 12:23:30 PM.

\MarkdownSharp-master\MarkdownSharp.sln" (1) is building
 "C:\Users\b-sarajr\Documents\SB\3. Project Files\1. MEC\MarkdownSharp-master\MarkdownSharp\MarkdownSharp.csproj" (2) o
n node 1 (default targets).
_HandlePackageFileConflicts:
  Encountered conflict between 'Platform:System.DirectoryServices.AccountManagement.dll' and 'Platform:System.Directory
  Services.AccountManagement.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Net.dll' and 'Platform:System.Net.dll'.  Could not determine winner due
   to equal file and assembly versions.
  Encountered conflict between 'Platform:System.ComponentModel.DataAnnotations.dll' and 'Platform:System.ComponentModel
  .DataAnnotations.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Abstractions.dll' and 'Platform:System.Web.Abstractions.dll'.  Coul
  d not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Routing.dll' and 'Platform:System.Web.Routing.dll'.  Could not dete
  rmine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.DynamicData.dll' and 'Platform:System.Web.DynamicData.dll'.  Could
  not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.DynamicData.Design.dll' and 'Platform:System.Web.DynamicData.Design
  .dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Extensions.Design.dll' and 'Platform:System.Web.Extensions.Design.d
  ll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Extensions.dll' and 'Platform:System.Web.Extensions.dll'.  Could no
  t determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Core.dll' and 'Platform:System.Core.dll'.  Could not determine winner d
  ue to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Conversion.v3.5.dll' and 'Platform:Microsoft.Build.Conversion.
  v3.5.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Utilities.v3.5.dll' and 'Platform:Microsoft.Build.Utilities.v3
  .5.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Tasks.v3.5.dll' and 'Platform:Microsoft.Build.Tasks.v3.5.dll'.
    Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Engine.dll' and 'Platform:Microsoft.Build.Engine.dll'.  Could
  not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Framework.dll' and 'Platform:Microsoft.Build.Framework.dll'.
  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.DataSetExtensions.dll' and 'Platform:System.Data.DataSetExtensions
  .dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.AddIn.dll' and 'Platform:System.AddIn.dll'.  Could not determine winner
   due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.AddIn.Contract.dll' and 'Platform:System.AddIn.Contract.dll'.  Could no
  t determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Linq.dll' and 'Platform:System.Data.Linq.dll'.  Could not determin
  e winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Xml.Linq.dll' and 'Platform:System.Xml.Linq.dll'.  Could not determine
  winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Management.Instrumentation.dll' and 'Platform:System.Management.Instrum
  entation.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.ServiceModel.Web.dll' and 'Platform:System.ServiceModel.Web.dll'.  Coul
  d not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.WorkflowServices.dll' and 'Platform:System.WorkflowServices.dll'.  Coul
  d not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.VisualC.STLCLR.dll' and 'Platform:Microsoft.VisualC.STLCLR.dll'.  Co
  uld not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.VisualC.STLCLR.dll' and 'Platform:Microsoft.VisualC.STLCLR.dll'.  Co
  uld not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Windows.Presentation.dll' and 'Platform:System.Windows.Presentation.dll
  '.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Sentinel.v3.5Client.dll' and 'Platform:Sentinel.v3.5Client.dll'.  Could not de
  termine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Entity.dll' and 'Platform:System.Data.Entity.dll'.  Could not dete
  rmine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Entity.Design.dll' and 'Platform:System.Data.Entity.Design.dll'.
  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Entity.dll' and 'Platform:System.Web.Entity.dll'.  Could not determ
  ine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Entity.Design.dll' and 'Platform:System.Web.Entity.Design.dll'.  Co
  uld not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Services.dll' and 'Platform:System.Data.Services.dll'.  Could not
  determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Services.Client.dll' and 'Platform:System.Data.Services.Client.dll
  '.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Services.Design.dll' and 'Platform:System.Data.Services.Design.dll
  '.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Engine.dll' and 'Platform:Microsoft.Build.Engine.dll'.  Choosi
  ng 'Platform:Microsoft.Build.Engine.dll' because AssemblyVersion '3.5.0.0' is greater than '2.0.0.0'.
  Encountered conflict between 'Platform:Microsoft.Build.Framework.dll' and 'Platform:Microsoft.Build.Framework.dll'.
  Choosing 'Platform:Microsoft.Build.Framework.dll' because AssemblyVersion '3.5.0.0' is greater than '2.0.0.0'.
  Encountered conflict between 'Platform:MSBuild.dll' and 'Platform:MSBuild.dll'.  Choosing 'Platform:MSBuild.dll' beca
  use AssemblyVersion '3.5.0.0' is greater than '2.0.0.0'.
  Encountered conflict between 'Platform:System.DirectoryServices.AccountManagement.dll' and 'Platform:System.Directory
  Services.AccountManagement.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Net.dll' and 'Platform:System.Net.dll'.  Could not determine winner due
   to equal file and assembly versions.
  Encountered conflict between 'Platform:System.ComponentModel.DataAnnotations.dll' and 'Platform:System.ComponentModel
  .DataAnnotations.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Abstractions.dll' and 'Platform:System.Web.Abstractions.dll'.  Coul
  d not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Routing.dll' and 'Platform:System.Web.Routing.dll'.  Could not dete
  rmine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.DynamicData.dll' and 'Platform:System.Web.DynamicData.dll'.  Could
  not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.DynamicData.Design.dll' and 'Platform:System.Web.DynamicData.Design
  .dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Extensions.Design.dll' and 'Platform:System.Web.Extensions.Design.d
  ll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Extensions.dll' and 'Platform:System.Web.Extensions.dll'.  Could no
  t determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Core.dll' and 'Platform:System.Core.dll'.  Could not determine winner d
  ue to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Conversion.v3.5.dll' and 'Platform:Microsoft.Build.Conversion.
  v3.5.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Utilities.v3.5.dll' and 'Platform:Microsoft.Build.Utilities.v3
  .5.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Tasks.v3.5.dll' and 'Platform:Microsoft.Build.Tasks.v3.5.dll'.
    Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Engine.dll' and 'Platform:Microsoft.Build.Engine.dll'.  Could
  not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Framework.dll' and 'Platform:Microsoft.Build.Framework.dll'.
  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.DataSetExtensions.dll' and 'Platform:System.Data.DataSetExtensions
  .dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.AddIn.dll' and 'Platform:System.AddIn.dll'.  Could not determine winner
   due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.AddIn.Contract.dll' and 'Platform:System.AddIn.Contract.dll'.  Could no
  t determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Linq.dll' and 'Platform:System.Data.Linq.dll'.  Could not determin
  e winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Xml.Linq.dll' and 'Platform:System.Xml.Linq.dll'.  Could not determine
  winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Management.Instrumentation.dll' and 'Platform:System.Management.Instrum
  entation.dll'.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.ServiceModel.Web.dll' and 'Platform:System.ServiceModel.Web.dll'.  Coul
  d not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.WorkflowServices.dll' and 'Platform:System.WorkflowServices.dll'.  Coul
  d not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.VisualC.STLCLR.dll' and 'Platform:Microsoft.VisualC.STLCLR.dll'.  Co
  uld not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.VisualC.STLCLR.dll' and 'Platform:Microsoft.VisualC.STLCLR.dll'.  Co
  uld not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Windows.Presentation.dll' and 'Platform:System.Windows.Presentation.dll
  '.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Sentinel.v3.5Client.dll' and 'Platform:Sentinel.v3.5Client.dll'.  Could not de
  termine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Entity.dll' and 'Platform:System.Data.Entity.dll'.  Could not dete
  rmine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Entity.Design.dll' and 'Platform:System.Data.Entity.Design.dll'.
  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Entity.dll' and 'Platform:System.Web.Entity.dll'.  Could not determ
  ine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Web.Entity.Design.dll' and 'Platform:System.Web.Entity.Design.dll'.  Co
  uld not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Services.dll' and 'Platform:System.Data.Services.dll'.  Could not
  determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Services.Client.dll' and 'Platform:System.Data.Services.Client.dll
  '.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:System.Data.Services.Design.dll' and 'Platform:System.Data.Services.Design.dll
  '.  Could not determine winner due to equal file and assembly versions.
  Encountered conflict between 'Platform:Microsoft.Build.Engine.dll' and 'Platform:Microsoft.Build.Engine.dll'.  Choosi
  ng 'Platform:Microsoft.Build.Engine.dll' because AssemblyVersion '3.5.0.0' is greater than '2.0.0.0'.
  Encountered conflict between 'Platform:Microsoft.Build.Framework.dll' and 'Platform:Microsoft.Build.Framework.dll'.
  Choosing 'Platform:Microsoft.Build.Framework.dll' because AssemblyVersion '3.5.0.0' is greater than '2.0.0.0'.
  Encountered conflict between 'Platform:MSBuild.dll' and 'Platform:MSBuild.dll'.  Choosing 'Platform:MSBuild.dll' beca
  use AssemblyVersion '3.5.0.0' is greater than '2.0.0.0'.
CoreCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin\Roslyn\csc.exe /noconfig /nowarn:17
  01,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE /highentropyva- /reference:C:\Windows\Microsoft.NE
  T\Framework\v2.0.50727\mscorlib.dll /reference:C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Configuration.dll
   /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Core.dll" /reference:C:\Wind
  ows\Microsoft.NET\Framework\v2.0.50727\System.dll /debug+ /debug:full /filealign:512 /optimize- /out:obj\Debug\Markdo
  wnSharp.exe /ruleset:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Team Tools\Static Analysis Too
  ls\\Rule Sets\AllRules.ruleset" /target:winexe /utf8output Markdown.cs MarkdownOld.cs
  Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\Profession
  al\MSBuild\15.0\bin\Roslyn
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point [C:\MarkdownSharp-master\MarkdownSharp\MarkdownSharp.csproj]
Done Building Project "C:\MarkdownSharp-master\MarkdownSharp\Markdo
wnSharp.csproj" (default targets) -- FAILED.

Done Building Project "C:\MarkdownSharp-master\MarkdownSharp.sln" (
default targets) -- FAILED.`

Not able to build the solution

**Comment by NickCraver** [comment]
The build has been completely overhauled and should now work appropriately. There's a `build.cmd` in the root for convenience.
